### ISSUE TITLE
Can’t create payload first-user

### ISSUE THREAD

**Issue by Julesdj** [lgoodcode/payload#1]
Thank you guys for providing this template, it’s incredible and i believe it will help a lot of people in the future. I just detected a little bug in your access control and validation logics and wanted to let know.
The Issue : With the current implementation, the create operation requires knowing the user's role. Which returns undefined since we don’t have any users in the database at first , so the app throws an error. It will be great if you can check it out.

**Comment by lgoodcode** [comment]
Cool. I haven't used this in a while but I'll check it out later when I get a chance. If you want to try tackling it and making a pull request, that'd also be greatly appreciated!
